[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.3.2"

[context.deploy-preview]
  command = "yarn build-preview"

[[plugins]]
package = "netlify-plugin-rss"
  [plugins.inputs]
  # required configs, customize as needed
  dirToScan = "/post" # a subfolder to scan. "/" to scan all
  authorName = "Tenemos ELA Uruguay"
  site_url = "https://tenemosela.org.uy"
  title = "Noticias - Tenemos ELA Uruguay"
  rssDescription = "RSS Feed de Noticias de Tenemos ELA"
  categories = []

  # # optional configs, defaults shown
  # rssFaviconUrl = "https://swyx.io/favicon.png"
  # docs = "http://example.com/rss/docs.html"
  # managingEditor = "authorName"
  # webMaster = "authorName"
  # copyright = "2020 ${authorName}"
  # language = "en"
  # pubDate = "new Date().toUTCString(),"
  # ttl = "60" # aka refresh every hour

  # # cheerio selectors for extractMetadataFromFile
  # # defaults shown
  # contentSelector = "main"
  # publishDateSelector = # if not specified, we use the date of file creation
  # descriptionSelector = "meta[name=description]" # probably no need to change
  # titleSelector = "title" # probably no need to change

  # # developer configs
  # debugMode = false # (for development) turn true for extra diagnostic logging
